### PR TITLE
Test PR preview

### PR DESCRIPTION
**Pull request by milanmlft**
Testing sandpaper's built-in PR previews for #12

>[!warning]
>This PR just adds nonsense content and is not supposed to be merged!

### CODE REVIEW

**Comment by davecash75** [comment]
Sorry I'm not sure how I can check the rendered content? I'm just getting the standard diff view of the files between the original and the current branch. Should I be seeing some rendered markdown side by side?

**Comment by milanmlft** [comment]
Hi @davecash75, *sandpaper*'s PR preview doesn't show the rendered content, only the diff view of the (raw) content that has changed. To see the rendered content, you would have to pull the branch and rebuild locally.

**Comment by davecash75** [comment]
@milanmlft Do I have to compile sandpaper from the forked repo if I am to build the files locally?

**Comment by milanmlft** [comment]
@davecash75 Correct! Let me write up some installation instructions (I should probably also add these somewhere more visisble in the repo):

You should be able to run all of these from within R

```r
## Install remotes package
install.packages("remotes")

## Install sandpaper and varnish from the IDEAS forks
remotes::install_github("HealthBioscienceIDEAS/sandpaper", dependencies = TRUE)
remotes::install_github("HealthBioscienceIDEAS/varnish", dependencies = TRUE)
```

Then to build the lesson locally, from within the `microscopy-novice` directory, run

```r
sandpaper::build_site()
```

That _should_ open the built home page in a browser window automatically, but if not, you can find the built HTML files in the `site/` directory :) 

Let me know if this works!

**Comment by davecash75** [comment]
I needed a couple of additional dependencies via homebrew for some of the other dependencies, mainly due to missing include files: openssl, harfbuzz, and fribidi. Installing those now and see if the install_github will then finish

**Comment by davecash75** [comment]
Hi @milanmlft -
I'm able to build locally, so I can take a look at @K-Meech 's first episode. I got an error when I tried
```r
sandpaper::build_site()
```
as it appears to be an internal function when I built it with the `remotes::install_github()` method. When I looked at the documentation on sandpaper, it seemed to suggest
```r
sandpaper::build_lesson()
```

**Comment by milanmlft** [comment]
Oh right, sorry about that! `build_lesson()` is the correct method 🙂

**Pull request closed without merging**
